import 'package:flutter/material.dart';
import 'package:portal/shared/styles.dart';

class DefaultTextFormField extends TextFormField {
  DefaultTextFormField(
      {super.key,
      super.controller,
      super.initialValue,
      super.focusNode,
      super.keyboardType,
      super.textCapitalization,
      super.textInputAction,
      super.strutStyle,
      super.textDirection,
      super.textAlign,
      super.textAlignVertical,
      super.autofocus,
      super.readOnly,
      super.toolbarOptions,
      super.showCursor,
      super.obscuringCharacter,
      super.obscureText,
      super.autocorrect,
      super.smartDashesType,
      super.smartQuotesType,
      super.enableSuggestions,
      super.maxLengthEnforcement,
      super.maxLines,
      super.minLines,
      super.expands,
      super.maxLength,
      super.onChanged,
      super.onTap,
      super.onTapAlwaysCalled,
      super.onTapOutside,
      super.onEditingComplete,
      super.onFieldSubmitted,
      super.onSaved,
      super.validator,
      super.inputFormatters,
      super.enabled,
      super.cursorWidth,
      super.cursorHeight,
      super.cursorRadius,
      super.cursorColor,
      super.cursorErrorColor,
      super.keyboardAppearance,
      super.scrollPadding,
      super.enableInteractiveSelection,
      super.selectionControls,
      super.buildCounter,
      super.scrollPhysics,
      super.autofillHints,
      super.autovalidateMode,
      super.scrollController,
      super.restorationId,
      super.enableIMEPersonalizedLearning,
      super.mouseCursor,
      super.contextMenuBuilder,
      super.spellCheckConfiguration,
      super.magnifierConfiguration,
      super.undoController,
      super.onAppPrivateCommand,
      super.cursorOpacityAnimates,
      super.selectionHeightStyle,
      super.selectionWidthStyle,
      super.dragStartBehavior,
      super.contentInsertionConfiguration,
      super.statesController,
      super.clipBehavior,
      super.scribbleEnabled,
      super.canRequestFocus,
      String? hintText,
      double? fontSize = 24,
      Widget? prefixIcon,
      Widget? suffixIcon,
      Widget? label})
      : super(
            style: TextStyle(color: Styles.text, fontSize: fontSize),
            decoration: InputDecoration(
                label: label,
                prefixIcon: prefixIcon,
                suffixIcon: suffixIcon,
                hintText: hintText,
                hintStyle: TextStyle(color: Styles.accent, fontSize: fontSize),
                contentPadding:
                    const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(Styles.borderB),
                    borderSide: BorderSide.none),
                filled: true,
                fillColor: Styles.backgroud));
}
